const funnelData = [
  {
    "no": 1,
    "principal": "ATS",
    "pic": "GIRI SURYANTO",
    "instansi": "Bawaslu",
    "wilayah": "Kota Administrasi Jakarta Pusat",
    "provinsi": "DKI Jakarta",
    "namaPaket": "Belanja Modal alat dan mesin",
    "sumberDana": "APBN",
    "nilaiAnggaran": 1000000000.0,
    "forecastNetto": 810810810.8108108,
    "produk": "Cetak Buku",
    "jenisProduk": "Cetak, Kertas, dan Buku Tulis",
    "quarter": "Q3",
    "tk": "50%\nJika Ada Peluang Untuk Menang Atau Sudah Dipanggil Klarifikasi"
  },
  {
    "no": 2,
    "principal": "SKE",
    "pic": "GIRI SURYANTO",
    "instansi": "KPU RI",
    "wilayah": "Kota Administrasi Jakarta Pusat",
    "provinsi": "DKI Jakarta",
    "namaPaket": "Pengadaan olah data CPNS",
    "sumberDana": "APBN",
    "nilaiAnggaran": 0.0,
    "forecastNetto": 0.0,
    "produk": "Laptop",
    "jenisProduk": "TIK & Periperal",
    "quarter": "Q4",
    "tk": "50%\nJika Ada Peluang Untuk Menang Atau Sudah Dipanggil Klarifikasi"
  },
  {
    "no": 3,
    "principal": "ATS",
    "pic": "DIKKY MAHISA PUTERA",
    "instansi": "Kementrian sosial",
    "wilayah": "Kota Bandar Lampung",
    "provinsi": "Lampung",
    "namaPaket": "Paket pengadaan Meubelair",
    "sumberDana": "APBN",
    "nilaiAnggaran": 1260000000.0,
    "forecastNetto": 1135135135.135135,
    "produk": "Meubelair",
    "jenisProduk": "Mebel / Furnitur",
    "quarter": "Q3",
    "tk": "50%\nJika Ada Peluang Untuk Menang Atau Sudah Dipanggil Klarifikasi"
  },
  {
    "no": 4,
    "principal": "Un categories",
    "pic": "DIKKY MAHISA PUTERA",
    "instansi": "kementrian Kesehatan",
    "wilayah": "Kabupaten Penajam Paser Utara",
    "provinsi": "Kalimantan Timur",
    "namaPaket": "Paket pengadaan IPAL",
    "sumberDana": "APBD",
    "nilaiAnggaran": 800000000.0,
    "forecastNetto": 720720720.7207206,
    "produk": "IPAL",
    "jenisProduk": "Paket Project",
    "quarter": "Q2",
    "tk": "50%\nJika Ada Peluang Untuk Menang Atau Sudah Dipanggil Klarifikasi"
  },
  {
    "no": 5,
    "principal": "Un categories",
    "pic": "DIKKY MAHISA PUTERA",
    "instansi": "Kementan",
    "wilayah": "Kabupaten Malang",
    "provinsi": "Jawa Timur",
    "namaPaket": "Paket pengadaan Pupuk",
    "sumberDana": "APBD",
    "nilaiAnggaran": 700000000.0,
    "forecastNetto": 630630630.6306306,
    "produk": "Pupuk",
    "jenisProduk": "Paket Project",
    "quarter": "Q2",
    "tk": "50%\nJika Ada Peluang Untuk Menang Atau Sudah Dipanggil Klarifikasi"
  },
  {
    "no": 6,
    "principal": "ATS",
    "pic": "DANANG SETYO BUDI",
    "instansi": "Dinas Pendidikan Kutai Timur",
    "wilayah": "Kabupaten Kutai Timur",
    "provinsi": "Kalimantan Timur",
    "namaPaket": "Paket pengadaan meubel",
    "sumberDana": "APBD",
    "nilaiAnggaran": 6489999430.0,
    "forecastNetto": 5846846333.333333,
    "produk": "MEUBELAIR",
    "jenisProduk": "Mebel / Furnitur",
    "quarter": "Q2",
    "tk": "100%\nClosing/Masuk PO"
  },
  {
    "no": 7,
    "principal": "SMK",
    "pic": "DANANG SETYO BUDI",
    "instansi": "Dinas Pendidikan Kutai Timur",
    "wilayah": "Kabupaten Kutai Timur",
    "provinsi": "Kalimantan Timur",
    "namaPaket": "Paket pengadaan ATK",
    "sumberDana": "APBD",
    "nilaiAnggaran": 2499999810.0,
    "forecastNetto": 2252252081.081081,
    "produk": "ATK",
    "jenisProduk": "Alat Tulis Kantor",
    "quarter": "Q2",
    "tk": "100%\nClosing/Masuk PO"
  },
  {
    "no": 8,
    "principal": "SKE",
    "pic": "DANANG SETYO BUDI",
    "instansi": "Dinas Pendidikan Kutai Timur",
    "wilayah": "Kabupaten Kutai Timur",
    "provinsi": "Kalimantan Timur",
    "namaPaket": "Paket pengadaan seragam dan meubel",
    "sumberDana": "APBD",
    "nilaiAnggaran": 30000000000.0,
    "forecastNetto": 27027027027.027023,
    "produk": "Seragam/meubel",
    "jenisProduk": "Paket Project",
    "quarter": "Q2",
    "tk": "75%\nSudah Masuk Dalam Short-List Atau Kemungkinan Besar untuk Menang"
  },
  {
    "no": 9,
    "principal": "SMK",
    "pic": "DANANG SETYO BUDI",
    "instansi": "Kemenag",
    "wilayah": "Kota Yogyakarta",
    "provinsi": "Daerah Istimewa Yogyakarta",
    "namaPaket": "Paket pengadaan ATK",
    "sumberDana": "APBN",
    "nilaiAnggaran": 10000000000.0,
    "forecastNetto": 9009009009.009008,
    "produk": "ATK",
    "jenisProduk": "Alat Tulis Kantor",
    "quarter": "Q2",
    "tk": "75%\nSudah Masuk Dalam Short-List Atau Kemungkinan Besar untuk Menang"
  },
  {
    "no": 10,
    "principal": "SMK",
    "pic": "DANANG SETYO BUDI",
    "instansi": "Dimas Perhubungan",
    "wilayah": "Kota Semarang",
    "provinsi": "Jawa Tengah",
    "namaPaket": "Paket pengadaan PJU",
    "sumberDana": "APBN",
    "nilaiAnggaran": 15000000000.0,
    "forecastNetto": 15000000000.0,
    "produk": "ATK",
    "jenisProduk": "Alat Tulis Kantor",
    "quarter": "Q2",
    "tk": "50%\nJika Ada Peluang Untuk Menang Atau Sudah Dipanggil Klarifikasi"
  },
  {
    "no": 11,
    "principal": "IPE",
    "pic": "BAMBANG SURYANTO",
    "instansi": "Pendidikan",
    "wilayah": "Kabupaten Kolaka Utara",
    "provinsi": "Sulawesi Tenggara",
    "namaPaket": "Paket Buku Teks pendamping koding Ai",
    "sumberDana": "APBD",
    "nilaiAnggaran": 242400000.0,
    "forecastNetto": 242400000.0,
    "produk": "Buku Teks Pendamping Koding dan Kecerdasan Artifisial untuk SD",
    "jenisProduk": "Buku Teks Pendamping HET",
    "quarter": "Q2",
    "tk": "50%\nJika Ada Peluang Untuk Menang Atau Sudah Dipanggil Klarifikasi"
  },
  {
    "no": 12,
    "principal": "IPE",
    "pic": "BAMBANG SURYANTO",
    "instansi": "Pendidikan",
    "wilayah": "Kabupaten Kolaka Utara",
    "provinsi": "Sulawesi Tenggara",
    "namaPaket": "Paket Buku Teks pendamping koding Ai",
    "sumberDana": "APBD",
    "nilaiAnggaran": 135750000.0,
    "forecastNetto": 122297297.29729728,
    "produk": "Buku Teks Pendamping Koding dan Kecerdasan Artifisial untuk SMP",
    "jenisProduk": "Buku Teks Pendamping HET",
    "quarter": "Q2",
    "tk": "50%\nJika Ada Peluang Untuk Menang Atau Sudah Dipanggil Klarifikasi"
  },
  {
    "no": 13,
    "principal": "SMK",
    "pic": "BAMBANG SURYANTO",
    "instansi": "Pendidikan",
    "wilayah": "Kabupaten Kolaka Utara",
    "provinsi": "Sulawesi Tenggara",
    "namaPaket": "Paket alat olahraga SD",
    "sumberDana": "APBD",
    "nilaiAnggaran": 1957614400.0,
    "forecastNetto": 1763616576.5765765,
    "produk": "Alat Olahraga Jenjang SD",
    "jenisProduk": "Alat Olahraga",
    "quarter": "Q2",
    "tk": "50%\nJika Ada Peluang Untuk Menang Atau Sudah Dipanggil Klarifikasi"
  },
  {
    "no": 14,
    "principal": "ATS",
    "pic": "HERI IRWANSYAH",
    "instansi": "DINAS PERUMAHAN RAKYAT DAN KAWASAN PERMUKIMAN",
    "wilayah": "Kabupaten Boyolali",
    "provinsi": "Jawa Tengah",
    "namaPaket": "Paket Pengadaan Mebel",
    "sumberDana": "APBD",
    "nilaiAnggaran": 13393325.51403548,
    "forecastNetto": 12066059.021653585,
    "produk": "SOFA RUANG TAMU",
    "jenisProduk": "Mebel / Furnitur",
    "quarter": "Q2",
    "tk": "25%\nPenawaran (RAB) Sudah Dikirimkan ke Relasi"
  },
  {
    "no": 15,
    "principal": "ATS",
    "pic": "HERI IRWANSYAH",
    "instansi": "DINAS SOSIAL, PEMBERDAYAAN PEREMPUAN DAN PERLINDUNGAN ANAK",
    "wilayah": "Kabupaten Boyolali",
    "provinsi": "Jawa Tengah",
    "namaPaket": "Paket Pengadaan ATK",
    "sumberDana": "APBD",
    "nilaiAnggaran": 42858641.64491353,
    "forecastNetto": 38611388.86929147,
    "produk": "HIBAH ALAT SEKOLAH",
    "jenisProduk": "Alat Tulis Kantor",
    "quarter": "Q2",
    "tk": "25%\nPenawaran (RAB) Sudah Dikirimkan ke Relasi"
  },
  {
    "no": 16,
    "principal": "ATS",
    "pic": "HERI IRWANSYAH",
    "instansi": "DINAS PETERNAKAN",
    "wilayah": "Kabupaten Boyolali",
    "provinsi": "Jawa Tengah",
    "namaPaket": "Paket Pengadaan Mebel",
    "sumberDana": "APBD",
    "nilaiAnggaran": 16071990.616842575,
    "forecastNetto": 14479270.825984301,
    "produk": "LEMARI KAYU JATI",
    "jenisProduk": "Mebel / Furnitur",
    "quarter": "Q2",
    "tk": "25%\nPenawaran (RAB) Sudah Dikirimkan ke Relasi"
  },
  {
    "no": 17,
    "principal": "SKE",
    "pic": "HERI IRWANSYAH",
    "instansi": "INSPEKTORAT",
    "wilayah": "Kabupaten Boyolali",
    "provinsi": "Jawa Tengah",
    "namaPaket": "Paket Pengadaan Hibah",
    "sumberDana": "APBD",
    "nilaiAnggaran": 24000839.32115158,
    "forecastNetto": 21622377.766803224,
    "produk": "sarung, mukena , al Quran, Iqro",
    "jenisProduk": "Alat Praktik",
    "quarter": "Q2",
    "tk": "100%\nClosing/Masuk PO"
  },
  {
    "no": 18,
    "principal": "SKE",
    "pic": "HERI IRWANSYAH",
    "instansi": "KECAMATAN TERAS",
    "wilayah": "Kabupaten Boyolali",
    "provinsi": "Jawa Tengah",
    "namaPaket": "Paket Pengadaan TIK",
    "sumberDana": "APBD",
    "nilaiAnggaran": 16071990.616842575,
    "forecastNetto": 14479270.825984301,
    "produk": "PC (Personal Computer) Intel Core i7,HD 1 TB, RAM 8 GB",
    "jenisProduk": "TIK & Periperal",
    "quarter": "Q3",
    "tk": "25%\nPenawaran (RAB) Sudah Dikirimkan ke Relasi"
  },
  {
    "no": 19,
    "principal": "SMK",
    "pic": "BLASIUS DIMAS",
    "instansi": "SPPG Bantul Pundong Panjangrejo 2",
    "wilayah": "Kabupaten Bantul",
    "provinsi": "Daerah Istimewa Yogyakarta",
    "namaPaket": "Belanja Rutin",
    "sumberDana": "APBN",
    "nilaiAnggaran": 70421.80920962236,
    "forecastNetto": 63443.071360020134,
    "produk": "Sarung Tangan Karet (isi 100)",
    "jenisProduk": "Alat Kesehatan / Kebersihan",
    "quarter": "Q2",
    "tk": "25%\nPenawaran (RAB) Sudah Dikirimkan ke Relasi"
  },
  {
    "no": 20,
    "principal": "SMK",
    "pic": "BLASIUS DIMAS",
    "instansi": "SPPG Bantul Jetis Patalan",
    "wilayah": "Kabupaten Bantul",
    "provinsi": "Daerah Istimewa Yogyakarta",
    "namaPaket": "Belanja Rutin",
    "sumberDana": "APBN",
    "nilaiAnggaran": 70421.80920962236,
    "forecastNetto": 63443.071360020134,
    "produk": "Sarung Tangan Karet (isi 100)",
    "jenisProduk": "Alat Kesehatan / Kebersihan",
    "quarter": "Q2",
    "tk": "25%\nPenawaran (RAB) Sudah Dikirimkan ke Relasi"
  },
  {
    "no": 21,
    "principal": "SMK",
    "pic": "BLASIUS DIMAS",
    "instansi": "SPPG Bantul Jetis Patalan 2",
    "wilayah": "Kabupaten Bantul",
    "provinsi": "Daerah Istimewa Yogyakarta",
    "namaPaket": "Belanja Rutin",
    "sumberDana": "APBN",
    "nilaiAnggaran": 70421.80920962236,
    "forecastNetto": 63443.071360020134,
    "produk": "Sarung Tangan Karet (isi 100)",
    "jenisProduk": "Alat Kesehatan / Kebersihan",
    "quarter": "Q2",
    "tk": "25%\nPenawaran (RAB) Sudah Dikirimkan ke Relasi"
  },
  {
    "no": 22,
    "principal": "SMK",
    "pic": "BLASIUS DIMAS",
    "instansi": "SPPG Bantul Jetis Patalan 3",
    "wilayah": "Kabupaten Bantul",
    "provinsi": "Daerah Istimewa Yogyakarta",
    "namaPaket": "Belanja Rutin",
    "sumberDana": "APBN",
    "nilaiAnggaran": 70421.80920962236,
    "forecastNetto": 63443.071360020134,
    "produk": "Sarung Tangan Karet (isi 100)",
    "jenisProduk": "Alat Kesehatan / Kebersihan",
    "quarter": "Q2",
    "tk": "25%\nPenawaran (RAB) Sudah Dikirimkan ke Relasi"
  },
  {
    "no": 23,
    "principal": "SMK",
    "pic": "BLASIUS DIMAS",
    "instansi": "Puskesmas Semin 1",
    "wilayah": "Kabupaten Gunungkidul",
    "provinsi": "Daerah Istimewa Yogyakarta",
    "namaPaket": "Belanja Rutin",
    "sumberDana": "BLUD",
    "nilaiAnggaran": 57098.76422401813,
    "forecastNetto": 51440.328129746056,
    "produk": "Pembersih Lantai GUARDER 5L",
    "jenisProduk": "Alat Kesehatan / Kebersihan",
    "quarter": "Q2",
    "tk": "25%\nPenawaran (RAB) Sudah Dikirimkan ke Relasi"
  },
  {
    "no": 24,
    "principal": "SMK",
    "pic": "BLASIUS DIMAS",
    "instansi": "Puskesmas Semin 2",
    "wilayah": "Kabupaten Gunungkidul",
    "provinsi": "Daerah Istimewa Yogyakarta",
    "namaPaket": "Belanja Rutin",
    "sumberDana": "BLUD",
    "nilaiAnggaran": 57098.76422401813,
    "forecastNetto": 51440.328129746056,
    "produk": "Pembersih Lantai GUARDER 5L",
    "jenisProduk": "Alat Kesehatan / Kebersihan",
    "quarter": "Q2",
    "tk": "25%\nPenawaran (RAB) Sudah Dikirimkan ke Relasi"
  },
  {
    "no": 25,
    "principal": "SMK",
    "pic": "BLASIUS DIMAS",
    "instansi": "Puskesmas Tanjungsari",
    "wilayah": "Kabupaten Gunungkidul",
    "provinsi": "Daerah Istimewa Yogyakarta",
    "namaPaket": "Belanja Rutin",
    "sumberDana": "BLUD",
    "nilaiAnggaran": 57098.76422401813,
    "forecastNetto": 51440.328129746056,
    "produk": "Pembersih Lantai GUARDER 5L",
    "jenisProduk": "Alat Kesehatan / Kebersihan",
    "quarter": "Q2",
    "tk": "25%\nPenawaran (RAB) Sudah Dikirimkan ke Relasi"
  },
  {
    "no": 26,
    "principal": "SMK",
    "pic": "BLASIUS DIMAS",
    "instansi": "Puskesmas Tepus 1",
    "wilayah": "Kabupaten Gunungkidul",
    "provinsi": "Daerah Istimewa Yogyakarta",
    "namaPaket": "Belanja Rutin",
    "sumberDana": "BLUD",
    "nilaiAnggaran": 57098.76422401813,
    "forecastNetto": 51440.328129746056,
    "produk": "Pembersih Lantai GUARDER 5L",
    "jenisProduk": "Alat Kesehatan / Kebersihan",
    "quarter": "Q2",
    "tk": "25%\nPenawaran (RAB) Sudah Dikirimkan ke Relasi"
  },
  {
    "no": 27,
    "principal": "SMK",
    "pic": "BLASIUS DIMAS",
    "instansi": "Puskesmas Tepus 2",
    "wilayah": "Kabupaten Gunungkidul",
    "provinsi": "Daerah Istimewa Yogyakarta",
    "namaPaket": "Belanja Rutin",
    "sumberDana": "BLUD",
    "nilaiAnggaran": 57098.76422401813,
    "forecastNetto": 51440.328129746056,
    "produk": "Pembersih Lantai GUARDER 5L",
    "jenisProduk": "Alat Kesehatan / Kebersihan",
    "quarter": "Q2",
    "tk": "25%\nPenawaran (RAB) Sudah Dikirimkan ke Relasi"
  },
  {
    "no": 28,
    "principal": "SMK",
    "pic": "BLASIUS DIMAS",
    "instansi": "Puskesmas Wonosari 1",
    "wilayah": "Kabupaten Gunungkidul",
    "provinsi": "Daerah Istimewa Yogyakarta",
    "namaPaket": "Belanja Rutin",
    "sumberDana": "BLUD",
    "nilaiAnggaran": 57098.76422401813,
    "forecastNetto": 51440.328129746056,
    "produk": "Pembersih Lantai GUARDER 5L",
    "jenisProduk": "Alat Kesehatan / Kebersihan",
    "quarter": "Q2",
    "tk": "25%\nPenawaran (RAB) Sudah Dikirimkan ke Relasi"
  },
  {
    "no": 29,
    "principal": "ATS",
    "pic": "BLASIUS DIMAS",
    "instansi": "Puskesmas Wonosari 2",
    "wilayah": "Kabupaten Gunungkidul",
    "provinsi": "Daerah Istimewa Yogyakarta",
    "namaPaket": "Belanja Modal BLUD_Lemari Penyimpanan",
    "sumberDana": "BLUD",
    "nilaiAnggaran": 10080152.393036801,
    "forecastNetto": 9081218.372105226,
    "produk": "Lemari Arsip RIONE 5 Rak Pintu Ayun",
    "jenisProduk": "Mebel / Furnitur",
    "quarter": "Q2",
    "tk": "25%\nPenawaran (RAB) Sudah Dikirimkan ke Relasi"
  },
  {
    "no": 30,
    "principal": "ATS",
    "pic": "BLASIUS DIMAS",
    "instansi": "RSUD Prambanan",
    "wilayah": "Kabupaten Sleman",
    "provinsi": "Daerah Istimewa Yogyakarta",
    "namaPaket": "Belanja Modal BLUD-Mebeler",
    "sumberDana": "BLUD",
    "nilaiAnggaran": 43777305.3151979,
    "forecastNetto": 39439013.797475584,
    "produk": "Kursi Kerja RIONE Jaring Nautilus HT0A",
    "jenisProduk": "Mebel / Furnitur",
    "quarter": "Q3",
    "tk": "25%\nPenawaran (RAB) Sudah Dikirimkan ke Relasi"
  },
  {
    "no": 31,
    "principal": "ATS",
    "pic": "BLASIUS DIMAS",
    "instansi": "BPK RI PERWAKILAN PROVINSI DAERAH ISTIMEWA YOGYAKARTA",
    "wilayah": "Kota Yogyakarta",
    "provinsi": "Daerah Istimewa Yogyakarta",
    "namaPaket": "Belanja Modal Mebeler",
    "sumberDana": "APBN",
    "nilaiAnggaran": 12860544.995389681,
    "forecastNetto": 11586076.572423136,
    "produk": "Kursi Susun RIONE T-138",
    "jenisProduk": "Mebel / Furnitur",
    "quarter": "Q3",
    "tk": "25%\nPenawaran (RAB) Sudah Dikirimkan ke Relasi"
  },
  {
    "no": 32,
    "principal": "SKE",
    "pic": "BLASIUS DIMAS",
    "instansi": "RSUD Wonosari",
    "wilayah": "Kabupaten Gunungkidul",
    "provinsi": "Daerah Istimewa Yogyakarta",
    "namaPaket": "Belanja Modal Komputer",
    "sumberDana": "BLUD",
    "nilaiAnggaran": 22790971.740016833,
    "forecastNetto": 20532406.972988136,
    "produk": "PC Desktop Series Intel i5/8GB/512GB SSD/21.5inch/Win11/OHS21",
    "jenisProduk": "TIK & Periperal",
    "quarter": "Q3",
    "tk": "25%\nPenawaran (RAB) Sudah Dikirimkan ke Relasi"
  },
  {
    "no": 33,
    "principal": "SKE",
    "pic": "BLASIUS DIMAS",
    "instansi": "BADAN PERENCANAAN PEMBANGUNAN RISET DAN INOVASI DAERAH DIY",
    "wilayah": "Kota Yogyakarta",
    "provinsi": "Daerah Istimewa Yogyakarta",
    "namaPaket": "Belanja Modal Komputer",
    "sumberDana": "APBD",
    "nilaiAnggaran": 34146076.095104605,
    "forecastNetto": 30762230.716310453,
    "produk": "Laptop Intel Ci7/16GB/512GB/14 inch/Win11/OHS21",
    "jenisProduk": "TIK & Periperal",
    "quarter": "Q3",
    "tk": "25%\nPenawaran (RAB) Sudah Dikirimkan ke Relasi"
  },
  {
    "no": 34,
    "principal": "SKE",
    "pic": "BLASIUS DIMAS",
    "instansi": "BADAN KEUANGAN DAN ASET DAERAH",
    "wilayah": "Kabupaten Sleman",
    "provinsi": "Daerah Istimewa Yogyakarta",
    "namaPaket": "Belanja Modal Komputer",
    "sumberDana": "",
    "nilaiAnggaran": 31190517.172726706,
    "forecastNetto": 28099565.02047451,
    "produk": "PC AIO Intel Ci7/16GB/512GB/23,8inch/Win11/OHS21",
    "jenisProduk": "TIK & Periperal",
    "quarter": "Q3",
    "tk": "25%\nPenawaran (RAB) Sudah Dikirimkan ke Relasi"
  },
  {
    "no": 35,
    "principal": "IPV",
    "pic": "JOKO WALUYO",
    "instansi": "Perpusda Kalteng",
    "wilayah": "Kota Palangka Raya",
    "provinsi": "Kalimantan Tengah",
    "namaPaket": "Paket pengadaan Buku Perpustakaan",
    "sumberDana": "POKIR",
    "nilaiAnggaran": 1500000000.0,
    "forecastNetto": 1351351351.3513513,
    "produk": "Buku Perpustakaan",
    "jenisProduk": "Buku Non Teks HET",
    "quarter": "Q3",
    "tk": "50%\nJika Ada Peluang Untuk Menang Atau Sudah Dipanggil Klarifikasi"
  },
  {
    "no": 36,
    "principal": "ATS",
    "pic": "JOKO WALUYO",
    "instansi": "Perpusda Kalteng",
    "wilayah": "Kota Palangka Raya",
    "provinsi": "Kalimantan Tengah",
    "namaPaket": "Paket pengadaan meubelair",
    "sumberDana": "POKIR",
    "nilaiAnggaran": 300000000.0,
    "forecastNetto": 270270270.2702702,
    "produk": "Mebeler",
    "jenisProduk": "Mebel / Furnitur",
    "quarter": "Q3",
    "tk": "50%\nJika Ada Peluang Untuk Menang Atau Sudah Dipanggil Klarifikasi"
  },
  {
    "no": 37,
    "principal": "IPV",
    "pic": "JOKO WALUYO",
    "instansi": "Dinas Pendidikan Propinsi Kalteng",
    "wilayah": "Kota Palangka Raya",
    "provinsi": "Kalimantan Tengah",
    "namaPaket": "Paket pengadaan Perpustakaan",
    "sumberDana": "APBD",
    "nilaiAnggaran": 5000000000.0,
    "forecastNetto": 4504504504.504504,
    "produk": "Buku Perpustakaan",
    "jenisProduk": "Buku Non Teks HET",
    "quarter": "Q3",
    "tk": "50%\nJika Ada Peluang Untuk Menang Atau Sudah Dipanggil Klarifikasi"
  },
  {
    "no": 38,
    "principal": "IPV",
    "pic": "JOKO WALUYO",
    "instansi": "Dinas Kesehatan Kota Palangka Raya",
    "wilayah": "Kota Palangka Raya",
    "provinsi": "Kalimantan Tengah",
    "namaPaket": "Paket pengadaan Kesehatan",
    "sumberDana": "APBN",
    "nilaiAnggaran": 10000000000.0,
    "forecastNetto": 9009009009.009008,
    "produk": "Alat Kesehatan",
    "jenisProduk": "Alat Kesehatan / Kebersihan",
    "quarter": "Q3",
    "tk": "50%\nJika Ada Peluang Untuk Menang Atau Sudah Dipanggil Klarifikasi"
  },
  {
    "no": 39,
    "principal": "SMK",
    "pic": "LILIK LASONO",
    "instansi": "Dinas Pendidikan",
    "wilayah": "Kabupaten Kutai Barat",
    "provinsi": "Kalimantan Timur",
    "namaPaket": "Paket pengadaan Baju Seragam TK Negeri",
    "sumberDana": "APBD",
    "nilaiAnggaran": 565896000.0,
    "forecastNetto": 509816216.21621615,
    "produk": "Baju Seragam TK Negeri",
    "jenisProduk": "Pakaian dan Seragam",
    "quarter": "Q2",
    "tk": "75%\nSudah Masuk Dalam Short-List Atau Kemungkinan Besar untuk Menang"
  },
  {
    "no": 40,
    "principal": "ATS",
    "pic": "LILIK LASONO",
    "instansi": "Dinas Pendidikan",
    "wilayah": "Kabupaten Kutai Barat",
    "provinsi": "Kalimantan Timur",
    "namaPaket": "Paket pengadaan  OUT DOOR",
    "sumberDana": "APBD",
    "nilaiAnggaran": 110612250.0,
    "forecastNetto": 99650675.67567566,
    "produk": "APE OUT DOOR",
    "jenisProduk": "Alat Peraga APE Luar",
    "quarter": "Q2",
    "tk": "75%\nSudah Masuk Dalam Short-List Atau Kemungkinan Besar untuk Menang"
  },
  {
    "no": 41,
    "principal": "ATS",
    "pic": "LILIK LASONO",
    "instansi": "Dinas Pendidikan",
    "wilayah": "Kabupaten Kutai Barat",
    "provinsi": "Kalimantan Timur",
    "namaPaket": "Paket pengadaan  OUT DOOR",
    "sumberDana": "APBD",
    "nilaiAnggaran": 110612250.0,
    "forecastNetto": 99650675.67567566,
    "produk": "APE OUT DOOR",
    "jenisProduk": "Alat Peraga APE Luar",
    "quarter": "Q2",
    "tk": "75%\nSudah Masuk Dalam Short-List Atau Kemungkinan Besar untuk Menang"
  },
  {
    "no": 42,
    "principal": "SKE",
    "pic": "LILIK LASONO",
    "instansi": "Dinas Pendidikan",
    "wilayah": "Kabupaten Kutai Barat",
    "provinsi": "Kalimantan Timur",
    "namaPaket": "Paket pengadaan  IN DOOR",
    "sumberDana": "APBD",
    "nilaiAnggaran": 125227000.0,
    "forecastNetto": 112817117.1171171,
    "produk": "APE IN DOOR",
    "jenisProduk": "Alat Peraga APE Dalam",
    "quarter": "Q2",
    "tk": "75%\nSudah Masuk Dalam Short-List Atau Kemungkinan Besar untuk Menang"
  },
  {
    "no": 43,
    "principal": "SKE",
    "pic": "LILIK LASONO",
    "instansi": "Dinas Pendidikan",
    "wilayah": "Kabupaten Kutai Barat",
    "provinsi": "Kalimantan Timur",
    "namaPaket": "Paket pengadaan  IN DOOR",
    "sumberDana": "APBD",
    "nilaiAnggaran": 146846000.0,
    "forecastNetto": 132293693.69369368,
    "produk": "APE IN DOOR",
    "jenisProduk": "Alat Peraga APE Dalam",
    "quarter": "Q2",
    "tk": "75%\nSudah Masuk Dalam Short-List Atau Kemungkinan Besar untuk Menang"
  },
  {
    "no": 44,
    "principal": "IPV",
    "pic": "LILIK LASONO",
    "instansi": "Dinas Pendidikan",
    "wilayah": "Kabupaten Kutai Barat",
    "provinsi": "Kalimantan Timur",
    "namaPaket": "Paket pengadaan  Mewarnai TK /  PAUD",
    "sumberDana": "APBD",
    "nilaiAnggaran": 130000000.0,
    "forecastNetto": 117117117.1171171,
    "produk": "Buku Mewarnai TK /  PAUD",
    "jenisProduk": "Buku PAUD",
    "quarter": "Q2",
    "tk": "75%\nSudah Masuk Dalam Short-List Atau Kemungkinan Besar untuk Menang"
  },
  {
    "no": 45,
    "principal": "IPV",
    "pic": "LILIK LASONO",
    "instansi": "Dinas Pendidikan",
    "wilayah": "Kabupaten Kutai Barat",
    "provinsi": "Kalimantan Timur",
    "namaPaket": "Paket pengadaan  Kumer PAUD Usia 4-5 /  5 - 6",
    "sumberDana": "APBD",
    "nilaiAnggaran": 132730000.0,
    "forecastNetto": 119576576.57657656,
    "produk": "Buku Kumer PAUD Usia 4-5 /  5 - 6",
    "jenisProduk": "Buku PAUD",
    "quarter": "Q2",
    "tk": "75%\nSudah Masuk Dalam Short-List Atau Kemungkinan Besar untuk Menang"
  },
  {
    "no": 46,
    "principal": "ATS",
    "pic": "LILIK LASONO",
    "instansi": "Dinas Pendidikan",
    "wilayah": "Kabupaten Kutai Barat",
    "provinsi": "Kalimantan Timur",
    "namaPaket": "Paket pengadaan  Meja Kursi Siswa",
    "sumberDana": "APBD",
    "nilaiAnggaran": 1980000000.0,
    "forecastNetto": 1783783783.7837837,
    "produk": "Pengadaan Meja Kursi Siswa",
    "jenisProduk": "Mebel / Furnitur",
    "quarter": "Q2",
    "tk": "75%\nSudah Masuk Dalam Short-List Atau Kemungkinan Besar untuk Menang"
  },
  {
    "no": 47,
    "principal": "ATS",
    "pic": "LILIK LASONO",
    "instansi": "Dinas Pendidikan",
    "wilayah": "Kabupaten Kutai Barat",
    "provinsi": "Kalimantan Timur",
    "namaPaket": "Paket pengadaan  Meja Kursi Siswa PAUD",
    "sumberDana": "APBD",
    "nilaiAnggaran": 600000000.0,
    "forecastNetto": 540540540.5405405,
    "produk": "Pengadaan Meja Kursi Siswa PAUD",
    "jenisProduk": "Mebel / Furnitur",
    "quarter": "Q2",
    "tk": "75%\nSudah Masuk Dalam Short-List Atau Kemungkinan Besar untuk Menang"
  },
  {
    "no": 48,
    "principal": "ATS",
    "pic": "LILIK LASONO",
    "instansi": "Dinas Pendidikan",
    "wilayah": "Kabupaten Kutai Barat",
    "provinsi": "Kalimantan Timur",
    "namaPaket": "Paket pengadaan  Crayon",
    "sumberDana": "APBD",
    "nilaiAnggaran": 126479860.00000001,
    "forecastNetto": 113945819.81981982,
    "produk": "Pengadaan Crayon",
    "jenisProduk": "Alat Tulis Kantor",
    "quarter": "Q2",
    "tk": "75%\nSudah Masuk Dalam Short-List Atau Kemungkinan Besar untuk Menang"
  },
  {
    "no": 49,
    "principal": "IPE",
    "pic": "LILIK LASONO",
    "instansi": "Dinas Pendidikan",
    "wilayah": "Kabupaten Kutai Barat",
    "provinsi": "Kalimantan Timur",
    "namaPaket": "Paket Pengadaan Buku Cerita PAUD",
    "sumberDana": "APBD",
    "nilaiAnggaran": 135720000.0,
    "forecastNetto": 122270270.27027026,
    "produk": "Pengadaan Buku Cerita PAUD",
    "jenisProduk": "Buku Non Teks HET",
    "quarter": "Q2",
    "tk": "75%\nSudah Masuk Dalam Short-List Atau Kemungkinan Besar untuk Menang"
  },
  {
    "no": 50,
    "principal": "ATS",
    "pic": "LILIK LASONO",
    "instansi": "Dinas Pendidikan",
    "wilayah": "Kabupaten Kutai Barat",
    "provinsi": "Kalimantan Timur",
    "namaPaket": "Paket Pengadaan Meja Kerja",
    "sumberDana": "APBD",
    "nilaiAnggaran": 270000000.0,
    "forecastNetto": 243243243.24324322,
    "produk": "Pengadaan Meja Kerja",
    "jenisProduk": "Mebel / Furnitur",
    "quarter": "Q2",
    "tk": "75%\nSudah Masuk Dalam Short-List Atau Kemungkinan Besar untuk Menang"
  },
  {
    "no": 51,
    "principal": "ATS",
    "pic": "LILIK LASONO",
    "instansi": "Dinas Pendidikan",
    "wilayah": "Kabupaten Kutai Barat",
    "provinsi": "Kalimantan Timur",
    "namaPaket": "Paket Pengadaan Kursi Kerja",
    "sumberDana": "APBD",
    "nilaiAnggaran": 252000000.0,
    "forecastNetto": 227027027.027027,
    "produk": "Pengadaan Kursi Kerja",
    "jenisProduk": "Mebel / Furnitur",
    "quarter": "Q2",
    "tk": "75%\nSudah Masuk Dalam Short-List Atau Kemungkinan Besar untuk Menang"
  },
  {
    "no": 52,
    "principal": "ATS",
    "pic": "LILIK LASONO",
    "instansi": "Dinas Pendidikan",
    "wilayah": "Kabupaten Kutai Barat",
    "provinsi": "Kalimantan Timur",
    "namaPaket": "Paket Pengadaan Lemari Arsip",
    "sumberDana": "APBD",
    "nilaiAnggaran": 53200000.0,
    "forecastNetto": 47927927.927927926,
    "produk": "Pengadaan Lemari Arsip",
    "jenisProduk": "Mebel / Furnitur",
    "quarter": "Q2",
    "tk": "75%\nSudah Masuk Dalam Short-List Atau Kemungkinan Besar untuk Menang"
  },
  {
    "no": 53,
    "principal": "SKE",
    "pic": "LILIK LASONO",
    "instansi": "Dinas Pendidikan",
    "wilayah": "Kabupaten Penajam Paser Utara",
    "provinsi": "Kalimantan Timur",
    "namaPaket": "Paket Pengadaan Laptop",
    "sumberDana": "POKIR",
    "nilaiAnggaran": 1200000000.0,
    "forecastNetto": 1081081081.081081,
    "produk": "Laptop",
    "jenisProduk": "TIK & Periperal",
    "quarter": "Q3",
    "tk": "50%\nJika Ada Peluang Untuk Menang Atau Sudah Dipanggil Klarifikasi"
  },
  {
    "no": 54,
    "principal": "IPV",
    "pic": "MANAEK HENDRAWAN SITINJAK",
    "instansi": "Dinas Pendidikan",
    "wilayah": "Kabupaten Deli Serdang",
    "provinsi": "Sumatera Utara",
    "namaPaket": "Paket Pengadaan Nonteks untuk SD",
    "sumberDana": "APBD",
    "nilaiAnggaran": 500000000.0,
    "forecastNetto": 500000000.0,
    "produk": "Buku Nonteks untuk SD",
    "jenisProduk": "Buku Non Teks HET",
    "quarter": "Q3",
    "tk": "25%\nPenawaran (RAB) Sudah Dikirimkan ke Relasi"
  },
  {
    "no": 55,
    "principal": "ATS",
    "pic": "MANAEK HENDRAWAN SITINJAK",
    "instansi": "Dinas Pendidikan",
    "wilayah": "Kabupaten Deli Serdang",
    "provinsi": "Sumatera Utara",
    "namaPaket": "Paket Pengadaan Kursi Guru&Siswa, Lemari, Papan Tulis",
    "sumberDana": "APBD",
    "nilaiAnggaran": 1000000000.0,
    "forecastNetto": 1000000000.0,
    "produk": "Meja Kursi Guru&Siswa, Lemari, Papan Tulis",
    "jenisProduk": "Mebel / Furnitur",
    "quarter": "Q3",
    "tk": "25%\nPenawaran (RAB) Sudah Dikirimkan ke Relasi"
  },
  {
    "no": 56,
    "principal": "IPV",
    "pic": "MANAEK HENDRAWAN SITINJAK",
    "instansi": "Dinas Pendidikan",
    "wilayah": "Kabupaten Langkat",
    "provinsi": "Sumatera Utara",
    "namaPaket": "Paket Pengadaan Nonteks SD-SMP",
    "sumberDana": "APBD",
    "nilaiAnggaran": 1000000000.0,
    "forecastNetto": 900900900.9009008,
    "produk": "Buku Nonteks SD-SMP",
    "jenisProduk": "Buku Non Teks HET",
    "quarter": "Q3",
    "tk": "25%\nPenawaran (RAB) Sudah Dikirimkan ke Relasi"
  },
  {
    "no": 57,
    "principal": "IPV",
    "pic": "MANAEK HENDRAWAN SITINJAK",
    "instansi": "Dinas Pendidikan dan Kebudayaan",
    "wilayah": "Kota Subulussalam",
    "provinsi": "Nanggroe Aceh Darussalam",
    "namaPaket": "Paket Pengadaan Nonteks SD-SMP (obral)",
    "sumberDana": "APBD",
    "nilaiAnggaran": 2000000000.0,
    "forecastNetto": 1801801801.8018017,
    "produk": "Buku Nonteks SD-SMP (obral)",
    "jenisProduk": "Buku Non Teks HET",
    "quarter": "Q3",
    "tk": "25%\nPenawaran (RAB) Sudah Dikirimkan ke Relasi"
  },
  {
    "no": 58,
    "principal": "IPE",
    "pic": "MUHAMMAD RASYID RIDHA",
    "instansi": "Dinas Pendidikan dan Kebudayaan",
    "wilayah": "Kota Singkawang",
    "provinsi": "Kalimantan Barat",
    "namaPaket": "Paket pengadaan Buku Smartbook SD",
    "sumberDana": "APBD",
    "nilaiAnggaran": 400000000.0,
    "forecastNetto": 360360360.3603603,
    "produk": "Buku Smartbook SD",
    "jenisProduk": "Buku Non Teks",
    "quarter": "Q1",
    "tk": "100%\nClosing/Masuk PO"
  },
  {
    "no": 59,
    "principal": "IPE",
    "pic": "MUHAMMAD RASYID RIDHA",
    "instansi": "Dinas Pendidikan dan Kebudayaan",
    "wilayah": "Kota Singkawang",
    "provinsi": "Kalimantan Barat",
    "namaPaket": "Paket pengadaan Smartbook SMP",
    "sumberDana": "APBD",
    "nilaiAnggaran": 400000000.0,
    "forecastNetto": 360360360.3603603,
    "produk": "Buku Smartbook SMP",
    "jenisProduk": "Buku Non Teks",
    "quarter": "Q1",
    "tk": "100%\nClosing/Masuk PO"
  },
  {
    "no": 60,
    "principal": "IPE",
    "pic": "MUHAMMAD RASYID RIDHA",
    "instansi": "Dinas Pendidikan dan Kebudayaan",
    "wilayah": "Kota Singkawang",
    "provinsi": "Kalimantan Barat",
    "namaPaket": "Paket pengadaan Interaktif SD",
    "sumberDana": "APBD",
    "nilaiAnggaran": 800000000.0,
    "forecastNetto": 800000000.0,
    "produk": "Buku Interaktif SD",
    "jenisProduk": "Buku Teks Pendamping",
    "quarter": "Q1",
    "tk": "100%\nClosing/Masuk PO"
  },
  {
    "no": 61,
    "principal": "IPE",
    "pic": "MUHAMMAD RASYID RIDHA",
    "instansi": "Dinas Pendidikan dan Kebudayaan",
    "wilayah": "Kota Singkawang",
    "provinsi": "Kalimantan Barat",
    "namaPaket": "Paket pengadaan Interaktif SMP",
    "sumberDana": "APBD",
    "nilaiAnggaran": 700000000.0,
    "forecastNetto": 700000000.0,
    "produk": "Buku Interaktif SMP",
    "jenisProduk": "Buku Teks Pendamping",
    "quarter": "Q1",
    "tk": "100%\nClosing/Masuk PO"
  },
  {
    "no": 62,
    "principal": "ATS",
    "pic": "MUHAMMAD RASYID RIDHA",
    "instansi": "Dinas Pendidikan dan Kebudayaan",
    "wilayah": "Kota Singkawang",
    "provinsi": "Kalimantan Barat",
    "namaPaket": "Paket pengadaan Meubelair",
    "sumberDana": "APBD",
    "nilaiAnggaran": 200000000.0,
    "forecastNetto": 180180180.18018016,
    "produk": "Meubeler",
    "jenisProduk": "Mebel / Furnitur",
    "quarter": "Q1",
    "tk": "100%\nClosing/Masuk PO"
  },
  {
    "no": 63,
    "principal": "ATS",
    "pic": "MUHAMMAD RASYID RIDHA",
    "instansi": "Dinas Pendidikan dan Kebudayaan",
    "wilayah": "Kota Singkawang",
    "provinsi": "Kalimantan Barat",
    "namaPaket": "Paket pengadaan Meubeler SD",
    "sumberDana": "APBDP",
    "nilaiAnggaran": 1000000000.0,
    "forecastNetto": 900900900.9009008,
    "produk": "Meubeler SD",
    "jenisProduk": "Mebel / Furnitur",
    "quarter": "Q4",
    "tk": "25%\nPenawaran (RAB) Sudah Dikirimkan ke Relasi"
  },
  {
    "no": 64,
    "principal": "ATS",
    "pic": "MUHAMMAD RASYID RIDHA",
    "instansi": "Dinas Pendidikan dan Kebudayaan",
    "wilayah": "Kota Singkawang",
    "provinsi": "Kalimantan Barat",
    "namaPaket": "Paket pengadaan Meubeler SMP",
    "sumberDana": "APBDP",
    "nilaiAnggaran": 500000000.0,
    "forecastNetto": 450450450.4504504,
    "produk": "Meubeler SMP",
    "jenisProduk": "Mebel / Furnitur",
    "quarter": "Q4",
    "tk": "25%\nPenawaran (RAB) Sudah Dikirimkan ke Relasi"
  },
  {
    "no": 65,
    "principal": "ATS",
    "pic": "EKO JULIANTO",
    "instansi": "Dinas Pendidikan",
    "wilayah": "Kabupaten Ketapang",
    "provinsi": "Kalimantan Barat",
    "namaPaket": "Paket pengadaan Mebel",
    "sumberDana": "APBD",
    "nilaiAnggaran": 1000000000.0,
    "forecastNetto": 1000000000.0,
    "produk": "Mebel",
    "jenisProduk": "Mebel / Furnitur",
    "quarter": "Q2",
    "tk": "75%\nSudah Masuk Dalam Short-List Atau Kemungkinan Besar untuk Menang"
  },
  {
    "no": 66,
    "principal": "IPE",
    "pic": "EKO JULIANTO",
    "instansi": "Dinas Pendidikan",
    "wilayah": "Kabupaten Ketapang",
    "provinsi": "Kalimantan Barat",
    "namaPaket": "Paket pengadaan buku non teks",
    "sumberDana": "APBD",
    "nilaiAnggaran": 1000000000.0,
    "forecastNetto": 1000000000.0,
    "produk": "Buku",
    "jenisProduk": "Buku Non Teks HET",
    "quarter": "Q2",
    "tk": "75%\nSudah Masuk Dalam Short-List Atau Kemungkinan Besar untuk Menang"
  },
  {
    "no": 67,
    "principal": "IPE",
    "pic": "EKO JULIANTO",
    "instansi": "Dinas Pendidikan Provinsi",
    "wilayah": "Kota Pontianak",
    "provinsi": "Kalimantan Barat",
    "namaPaket": "Paket pengadaan buku non teks",
    "sumberDana": "APBD",
    "nilaiAnggaran": 2800000000.0,
    "forecastNetto": 2522522522.5225224,
    "produk": "Buku",
    "jenisProduk": "Buku Non Teks HET",
    "quarter": "Q3",
    "tk": "50%\nJika Ada Peluang Untuk Menang Atau Sudah Dipanggil Klarifikasi"
  },
  {
    "no": 68,
    "principal": "ATS",
    "pic": "EKO JULIANTO",
    "instansi": "Dinas Pendidikan",
    "wilayah": "Kabupaten Ketapang",
    "provinsi": "Kalimantan Barat",
    "namaPaket": "Paket pengadaan kertas raport",
    "sumberDana": "APBD",
    "nilaiAnggaran": 1500000000.0,
    "forecastNetto": 1500000000.0,
    "produk": "Kertas Raport",
    "jenisProduk": "Alat Tulis Kantor",
    "quarter": "Q4",
    "tk": "75%\nSudah Masuk Dalam Short-List Atau Kemungkinan Besar untuk Menang"
  },
  {
    "no": 69,
    "principal": "ATS",
    "pic": "YUDISTIRA WOLDI PAOKI",
    "instansi": "Dinas Perpustakaan dan Kearsipan",
    "wilayah": "Kabupaten Minahasa Tenggara",
    "provinsi": "Sulawesi Utara",
    "namaPaket": "Paket pengadaan meubel",
    "sumberDana": "APBN",
    "nilaiAnggaran": 500000000.0,
    "forecastNetto": 500000000.0,
    "produk": "Rione",
    "jenisProduk": "Mebel / Furnitur",
    "quarter": "Q2",
    "tk": "75%\nSudah Masuk Dalam Short-List Atau Kemungkinan Besar untuk Menang"
  },
  {
    "no": 70,
    "principal": "IPE",
    "pic": "YUDISTIRA WOLDI PAOKI",
    "instansi": "Dinas Perpustakaan dan Kearsipan",
    "wilayah": "Kabupaten Minahasa Tenggara",
    "provinsi": "Sulawesi Utara",
    "namaPaket": "Paket pengadaan Buku perpustakaan",
    "sumberDana": "APBN",
    "nilaiAnggaran": 200000000.0,
    "forecastNetto": 200000000.0,
    "produk": "Buku perpustakaan",
    "jenisProduk": "Buku Non Teks HET",
    "quarter": "Q2",
    "tk": "75%\nSudah Masuk Dalam Short-List Atau Kemungkinan Besar untuk Menang"
  },
  {
    "no": 71,
    "principal": "IPE",
    "pic": "YUDISTIRA WOLDI PAOKI",
    "instansi": "Dinas Pendidikan",
    "wilayah": "Kabupaten Minahasa",
    "provinsi": "Sulawesi Utara",
    "namaPaket": "Paket pengadaan Smartbook",
    "sumberDana": "APBD",
    "nilaiAnggaran": 150000000.0,
    "forecastNetto": 135135135.1351351,
    "produk": "Smartbook",
    "jenisProduk": "Buku Teks Pendamping",
    "quarter": "Q1",
    "tk": ""
  },
  {
    "no": 72,
    "principal": "SKE",
    "pic": "YUDISTIRA WOLDI PAOKI",
    "instansi": "Dinas Pendidikan",
    "wilayah": "Kabupaten Minahasa",
    "provinsi": "Sulawesi Utara",
    "namaPaket": "Paket pengadaan TIK",
    "sumberDana": "APBD",
    "nilaiAnggaran": 110000000.0,
    "forecastNetto": 110000000.0,
    "produk": "TIK",
    "jenisProduk": "TIK & Periperal",
    "quarter": "Q2",
    "tk": "100%\nClosing/Masuk PO"
  },
  {
    "no": 73,
    "principal": "SMK",
    "pic": "YUDISTIRA WOLDI PAOKI",
    "instansi": "Poltekes manado",
    "wilayah": "Kota Manado",
    "provinsi": "Sulawesi Utara",
    "namaPaket": "Paket pengadaan Seragam",
    "sumberDana": "APBN",
    "nilaiAnggaran": 886000000.0,
    "forecastNetto": 886000000.0,
    "produk": "Seragam",
    "jenisProduk": "Pakaian dan Seragam",
    "quarter": "Q2",
    "tk": "50%\nJika Ada Peluang Untuk Menang Atau Sudah Dipanggil Klarifikasi"
  },
  {
    "no": 74,
    "principal": "IPV",
    "pic": "YUDISTIRA WOLDI PAOKI",
    "instansi": "Poltekes Manado",
    "wilayah": "Kota Manado",
    "provinsi": "Sulawesi Utara",
    "namaPaket": "Paket pengadaan alat Lab",
    "sumberDana": "APBN",
    "nilaiAnggaran": 777962000.0,
    "forecastNetto": 777962000.0,
    "produk": "Lab",
    "jenisProduk": "Alat Peraga LAB IPA",
    "quarter": "Q2",
    "tk": "50%\nJika Ada Peluang Untuk Menang Atau Sudah Dipanggil Klarifikasi"
  },
  {
    "no": 75,
    "principal": "SKE",
    "pic": "YUDISTIRA WOLDI PAOKI",
    "instansi": "RS Noongan",
    "wilayah": "Kabupaten Minahasa",
    "provinsi": "Sulawesi Utara",
    "namaPaket": "Paket pengadaan ATK",
    "sumberDana": "APBN",
    "nilaiAnggaran": 250000000.0,
    "forecastNetto": 225225225.2252252,
    "produk": "ATK",
    "jenisProduk": "TIK & Periperal",
    "quarter": "Q1",
    "tk": "50%\nJika Ada Peluang Untuk Menang Atau Sudah Dipanggil Klarifikasi"
  },
  {
    "no": 76,
    "principal": "SKE",
    "pic": "AJI FARIZ RACHMAN",
    "instansi": "Puskesmas Matraman",
    "wilayah": "Kota Administrasi Jakarta Selatan",
    "provinsi": "DKI Jakarta",
    "namaPaket": "Paket pengadaan Printer Tinta",
    "sumberDana": "BLUD",
    "nilaiAnggaran": 8000000.0,
    "forecastNetto": 7207207.207207207,
    "produk": "Printer Tinta",
    "jenisProduk": "TIK & Periperal",
    "quarter": "Q3",
    "tk": "25%\nPenawaran (RAB) Sudah Dikirimkan ke Relasi"
  },
  {
    "no": 77,
    "principal": "SKE",
    "pic": "AJI FARIZ RACHMAN",
    "instansi": "BPOM",
    "wilayah": "Kota Administrasi Jakarta Pusat",
    "provinsi": "DKI Jakarta",
    "namaPaket": "Paket pengadaan Kamera",
    "sumberDana": "BLUD",
    "nilaiAnggaran": 75000000.0,
    "forecastNetto": 67567567.56756756,
    "produk": "Kamera",
    "jenisProduk": "Elektronik",
    "quarter": "Q3",
    "tk": "25%\nPenawaran (RAB) Sudah Dikirimkan ke Relasi"
  },
  {
    "no": 78,
    "principal": "SKE",
    "pic": "REZKI ANUGRAHA",
    "instansi": "Kesbangpol Provinsi Sumatera Barat",
    "wilayah": "Kota Padang",
    "provinsi": "Sumatera Barat",
    "namaPaket": "Pengadaan  ATK, Alat dan Bahan Komputer",
    "sumberDana": "APBD",
    "nilaiAnggaran": 23833800.0,
    "forecastNetto": 21471891.89189189,
    "produk": "ATK, Alat dan Bahan Komputer",
    "jenisProduk": "Alat Tulis Kantor",
    "quarter": "Q1",
    "tk": ""
  },
  {
    "no": 79,
    "principal": "SMK",
    "pic": "REZKI ANUGRAHA",
    "instansi": "DINAS KOMUNIKASI, INFORMATIKA DAN STATISTIK, Prov Sumbar",
    "wilayah": "Kota Padang",
    "provinsi": "Sumatera Barat",
    "namaPaket": "Pengadaan Alat Kebersihan dan Alat Kantor Habis Pakai",
    "sumberDana": "APBD",
    "nilaiAnggaran": 74050800.0,
    "forecastNetto": 66712432.43243243,
    "produk": "Alat Kebersihan dan Alat Kantor Habis Pakai",
    "jenisProduk": "Alat Kesehatan / Kebersihan",
    "quarter": "Q1",
    "tk": ""
  },
  {
    "no": 80,
    "principal": "SMK",
    "pic": "REZKI ANUGRAHA",
    "instansi": "Balai Karantina Hewan Ikan Dan Tumbuhan Sumatera Barat",
    "wilayah": "Kota Padang",
    "provinsi": "Sumatera Barat",
    "namaPaket": "Pengadaan pengadaan Pakaian Dinas Pegawai/perawat",
    "sumberDana": "APBN",
    "nilaiAnggaran": 102366000.0,
    "forecastNetto": 92221621.62162161,
    "produk": "Pakaian Dinas Pegawai/perawat",
    "jenisProduk": "Pakaian dan Seragam",
    "quarter": "Q2",
    "tk": "25%\nPenawaran (RAB) Sudah Dikirimkan ke Relasi"
  },
  {
    "no": 81,
    "principal": "SKE",
    "pic": "ATEP KUNAEPI",
    "instansi": "1.⁠ ⁠Dinas Pendikan Provinsi kalbar Alat Pendidikan",
    "wilayah": "Kota Pontianak",
    "provinsi": "Kalimantan Barat",
    "namaPaket": "Paket pengadaan Alat Pendidikan SMK",
    "sumberDana": "APBD",
    "nilaiAnggaran": 5000000000.0,
    "forecastNetto": 5000000000.0,
    "produk": "Alat Pendidikan SMK",
    "jenisProduk": "Alat Praktik SMK",
    "quarter": "Q3",
    "tk": "50%\nJika Ada Peluang Untuk Menang Atau Sudah Dipanggil Klarifikasi"
  },
  {
    "no": 82,
    "principal": "ATS",
    "pic": "ATEP KUNAEPI",
    "instansi": "2.⁠ ⁠⁠Dinas pendidikan Kota Pontianak Mebeler",
    "wilayah": "Kota Pontianak",
    "provinsi": "Kalimantan Barat",
    "namaPaket": "Paket pengadaan Mebelair",
    "sumberDana": "APBD",
    "nilaiAnggaran": 3000000000.0,
    "forecastNetto": 3000000000.0,
    "produk": "Mebelair",
    "jenisProduk": "Mebel / Furnitur",
    "quarter": "Q3",
    "tk": "50%\nJika Ada Peluang Untuk Menang Atau Sudah Dipanggil Klarifikasi"
  },
  {
    "no": 83,
    "principal": "ATS",
    "pic": "YUDHA PRATISTA APRIANATA",
    "instansi": "Perumda Tabanan",
    "wilayah": "Kabupaten Tabanan",
    "provinsi": "Bali",
    "namaPaket": "Paket pengadaan ATK & Elektronik",
    "sumberDana": "BUMD",
    "nilaiAnggaran": 2000000000.0,
    "forecastNetto": 1801801801.8018017,
    "produk": "ATK & Elektronik",
    "jenisProduk": "Alat Tulis Kantor",
    "quarter": "Q2",
    "tk": "50%\nJika Ada Peluang Untuk Menang Atau Sudah Dipanggil Klarifikasi"
  },
  {
    "no": 84,
    "principal": "ATS",
    "pic": "YUDHA PRATISTA APRIANATA",
    "instansi": "Puskesmas Denpasar Barat",
    "wilayah": "Kota Denpasar",
    "provinsi": "Bali",
    "namaPaket": "Paket pengadaan, ATK, Elektronik",
    "sumberDana": "BLUD",
    "nilaiAnggaran": 314000000.0,
    "forecastNetto": 282882882.88288283,
    "produk": "Mebel, ATK, Elektronik",
    "jenisProduk": "Paket Project",
    "quarter": "Q2",
    "tk": "25%\nPenawaran (RAB) Sudah Dikirimkan ke Relasi"
  },
  {
    "no": 85,
    "principal": "ATS",
    "pic": "AGUS MUHCLIS",
    "instansi": "Sekwan DPRD Kab.Bandung Barat",
    "wilayah": "Kabupaten Bandung Barat",
    "provinsi": "Jawa Barat",
    "namaPaket": "Paket pengadaan meja dan kursi",
    "sumberDana": "APBD",
    "nilaiAnggaran": 741300000.0,
    "forecastNetto": 667837837.8378378,
    "produk": "Kursi meja + stage",
    "jenisProduk": "Mebel / Furnitur",
    "quarter": "Q2",
    "tk": "75%\nSudah Masuk Dalam Short-List Atau Kemungkinan Besar untuk Menang"
  },
  {
    "no": 86,
    "principal": "ATS",
    "pic": "AGUS MUHCLIS",
    "instansi": "Sekwan DPRD Kab.Bandung Barat",
    "wilayah": "Kabupaten Bandung Barat",
    "provinsi": "Jawa Barat",
    "namaPaket": "Paket pengadaan ATK",
    "sumberDana": "APBD",
    "nilaiAnggaran": 211677200.0,
    "forecastNetto": 190700180.18018016,
    "produk": "Meubelair selasar gedung",
    "jenisProduk": "Alat Tulis Kantor",
    "quarter": "Q2",
    "tk": "25%\nPenawaran (RAB) Sudah Dikirimkan ke Relasi"
  },
  {
    "no": 87,
    "principal": "IPE",
    "pic": "BAMBANG MUDJIRAN",
    "instansi": "Sekretariat DPRD",
    "wilayah": "Kabupaten Bengkulu Tengah",
    "provinsi": "Bengkulu",
    "namaPaket": "Pengadaan Buku Bacaan Masyarakat",
    "sumberDana": "APBD",
    "nilaiAnggaran": 500000000.0,
    "forecastNetto": 450450450.4504504,
    "produk": "Pengadaan Buku Bacaan Masyarakat",
    "jenisProduk": "Buku Non Teks HET",
    "quarter": "Q2",
    "tk": "50%\nJika Ada Peluang Untuk Menang Atau Sudah Dipanggil Klarifikasi"
  },
  {
    "no": 88,
    "principal": "ATS",
    "pic": "BAMBANG MUDJIRAN",
    "instansi": "Sekretariat DPRD",
    "wilayah": "Kabupaten Bengkulu Tengah",
    "provinsi": "Bengkulu",
    "namaPaket": "Pengadaan Meubelair",
    "sumberDana": "APBD",
    "nilaiAnggaran": 500000000.0,
    "forecastNetto": 450450450.4504504,
    "produk": "Pengadaan Meubelair",
    "jenisProduk": "Mebel / Furnitur",
    "quarter": "Q2",
    "tk": "50%\nJika Ada Peluang Untuk Menang Atau Sudah Dipanggil Klarifikasi"
  },
  {
    "no": 89,
    "principal": "SKE",
    "pic": "RISKY ALDIANSYAH",
    "instansi": "POLRI",
    "wilayah": "Kota Administrasi Jakarta Timur",
    "provinsi": "DKI Jakarta",
    "namaPaket": "Paket pengadaan Alat Tulis",
    "sumberDana": "APBN",
    "nilaiAnggaran": 392200000.0,
    "forecastNetto": 353333333.3333333,
    "produk": "Zebra ZD23042-30PG00EZ",
    "jenisProduk": "Alat Tulis Kantor",
    "quarter": "Q2",
    "tk": "50%\nJika Ada Peluang Untuk Menang Atau Sudah Dipanggil Klarifikasi"
  },
  {
    "no": 90,
    "principal": "SKE",
    "pic": "RISKY ALDIANSYAH",
    "instansi": "POLRI",
    "wilayah": "Kota Administrasi Jakarta Timur",
    "provinsi": "DKI Jakarta",
    "namaPaket": "Paket pengadaan Alat Tulis",
    "sumberDana": "APBN",
    "nilaiAnggaran": 956040000.0,
    "forecastNetto": 861297297.2972972,
    "produk": "Zebra DS2208 SR7U2100SGW",
    "jenisProduk": "Alat Tulis Kantor",
    "quarter": "Q2",
    "tk": "50%\nJika Ada Peluang Untuk Menang Atau Sudah Dipanggil Klarifikasi"
  },
  {
    "no": 91,
    "principal": "SKE",
    "pic": "RISKY ALDIANSYAH",
    "instansi": "POLRI",
    "wilayah": "Kota Administrasi Jakarta Timur",
    "provinsi": "DKI Jakarta",
    "namaPaket": "Paket pengadaan Elektronik",
    "sumberDana": "APBN",
    "nilaiAnggaran": 4204400000.0,
    "forecastNetto": 3787747747.7477474,
    "produk": "Epson LQ2190",
    "jenisProduk": "Elektronik",
    "quarter": "Q2",
    "tk": "50%\nJika Ada Peluang Untuk Menang Atau Sudah Dipanggil Klarifikasi"
  },
  {
    "no": 92,
    "principal": "ATS",
    "pic": "FIKRI ARI HANAFI",
    "instansi": "DINAS KESEHATAN KAB.PEMALANG",
    "wilayah": "Kabupaten Pemalang",
    "provinsi": "Jawa Tengah",
    "namaPaket": "Paket pengadaan Meubel",
    "sumberDana": "APBD",
    "nilaiAnggaran": 1198820000.0,
    "forecastNetto": 1080018018.018018,
    "produk": "meja kursi lemari",
    "jenisProduk": "Mebel / Furnitur",
    "quarter": "Q3",
    "tk": "50%\nJika Ada Peluang Untuk Menang Atau Sudah Dipanggil Klarifikasi"
  },
  {
    "no": 93,
    "principal": "SKE",
    "pic": "FIKRI ARI HANAFI",
    "instansi": "DISKOMINFO KAB.PEMALANG",
    "wilayah": "Kabupaten Pemalang",
    "provinsi": "Jawa Tengah",
    "namaPaket": "Paket pengadaan periphearl",
    "sumberDana": "APBD",
    "nilaiAnggaran": 49020000.0,
    "forecastNetto": 44162162.162162155,
    "produk": "laptop printer",
    "jenisProduk": "TIK & Periperal",
    "quarter": "Q2",
    "tk": "50%\nJika Ada Peluang Untuk Menang Atau Sudah Dipanggil Klarifikasi"
  },
  {
    "no": 94,
    "principal": "SMK, ATS",
    "pic": "SALES PROJECT",
    "instansi": "PUSKESMAS, SPPG, RSUD, INTANSI DAERAH",
    "wilayah": "Indonesia",
    "provinsi": "Nasional",
    "namaPaket": "Paket pengadaan Bahan Kebersihan, Pengadaan Meubeler, Pengadaan Peripehal dll",
    "sumberDana": "APBD",
    "nilaiAnggaran": 56560000000.0,
    "forecastNetto": 50954954954.95495,
    "produk": "",
    "jenisProduk": "Paket Project",
    "quarter": "Q4",
    "tk": "50%\nJika Ada Peluang Untuk Menang Atau Sudah Dipanggil Klarifikasi"
  }
];
